# Generated by Django 5.0.3 on 2024-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0004_alter_imageupload_file_size_alter_imageupload_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='height',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='width',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='width',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='file_size',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='format',
            field=models.CharField(default='Image', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='Video', max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery')], default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='News', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery')], default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='format',
            field=models.CharField(default='Image', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='Banner', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery')], default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='Image', max_length=50),
        ),
    ]
