# Generated by Django 5.0.3 on 2024-07-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0005_remove_banner_height_remove_banner_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video',
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Image', max_length=30),
            preserve_default=False,
        ),
    ]
