# Generated by Django 4.2.9 on 2024-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0006_rename_file_video_video_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Facutly', 'Facutly')], default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Facutly', 'Facutly')], default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Facutly', 'Facutly')], default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Facutly', 'Facutly')], default='Home', max_length=50),
        ),
    ]
