# Generated by Django 4.2.9 on 2024-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0007_alter_imageupload_options_alter_banner_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='Banner', max_length=50),
        ),
    ]
