# Generated by Django 4.2.9 on 2024-08-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0008_alter_banner_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='Video', max_length=50),
        ),
    ]
