# Generated by Django 4.2.9 on 2024-08-19 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0010_alumni_collegeupdates_factulycount_faculty_mba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='phone_number',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
