# Generated by Django 4.2.9 on 2024-08-19 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0011_alter_studentform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
