# Generated by Django 5.0.3 on 2024-08-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0012_alter_studentform_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='Image', max_length=50),
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Facutly', 'Facutly')], default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='galleryvideos',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryvideos',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='galleryvideos',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='Image', max_length=50),
        ),
        migrations.AddField(
            model_name='galleryvideos',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Facutly', 'Facutly')], default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='galleryvideos',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='image',
            field=models.ImageField(upload_to='Gallery/photos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
