# Generated by Django 5.0.3 on 2024-08-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0013_galleryimages_file_size_galleryimages_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
