# Generated by Django 5.0.3 on 2024-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0014_alter_banner_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Facutly', 'Facutly')], default='Gallery', max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryvideos',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Facutly', 'Facutly')], default='Gallery', max_length=50),
        ),
    ]
