# Generated by Django 4.2.9 on 2024-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0015_alter_galleryimages_type_alter_galleryvideos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Faculty', 'Faculty')], default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Faculty', 'Faculty')], default='Gallery', max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryvideos',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Banner', 'Banner'), ('News', 'News')], default='Videos', max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryvideos',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Faculty', 'Faculty')], default='Gallery', max_length=50),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Faculty', 'Faculty')], default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Faculty', 'Faculty')], default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Faculty', 'Faculty')], default='Home', max_length=50),
        ),
    ]
