# Generated by Django 4.2.9 on 2024-08-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0016_alter_banner_type_alter_galleryimages_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='designation',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='Home/banners/'),
        ),
    ]
