# Generated by Django 4.2.9 on 2024-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0017_alumni_designation_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='heading',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryvideos',
            name='heading',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
