# Generated by Django 4.2.9 on 2024-08-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0018_galleryimages_heading_galleryvideos_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsandActivites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Gallery', 'Gallery'), ('Faculty', 'Faculty'), ('EventsandActivites', 'EventsandActivites')], default='EventsandActivites', max_length=50)),
                ('sub_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Images', max_length=50)),
                ('heading', models.CharField(max_length=100)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='EventsandActivites/Images/')),
                ('Video', models.FileField(upload_to='EventsandActivites/Videos/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
