# Generated by Django 4.2.9 on 2024-08-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0019_eventsandactivites_delete_imageupload_delete_news_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsandactivites',
            old_name='Image',
            new_name='image',
        ),
    ]
