# Generated by Django 4.2.9 on 2024-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0020_rename_image_eventsandactivites_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsandactivites',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='EventsandActivites/Videos/'),
        ),
        migrations.AlterField(
            model_name='eventsandactivites',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=50),
        ),
    ]
