# Generated by Django 4.2.9 on 2024-08-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0021_alter_eventsandactivites_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOnlineRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('permanent_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('mba', models.CharField(choices=[('Pursuing', 'Pursuing'), ('Passed', 'Passed')], default='Pursuing', max_length=10)),
                ('passed_year', models.IntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage_of_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cv_or_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
