# Generated by Django 4.2.9 on 2024-08-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0022_studentonlineregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentonlineregistration',
            old_name='mba',
            new_name='mba_status',
        ),
    ]
