# Generated by Django 4.2.9 on 2024-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0024_committees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committees',
            name='file',
            field=models.FileField(upload_to='committees/'),
        ),
    ]
