# Generated by Django 5.1 on 2024-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0025_alter_committees_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='committees',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
