# Generated by Django 5.1 on 2024-09-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0027_alter_faculty_mba_slno_alter_faculty_pharamacy_slno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_mba',
            name='slno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty_pharamacy',
            name='slno',
            field=models.IntegerField(),
        ),
    ]
