# Generated by Django 5.1 on 2024-09-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0028_alter_faculty_mba_slno_alter_faculty_pharamacy_slno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_mba',
            name='slno',
        ),
    ]
