# Generated by Django 5.1 on 2024-09-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0029_remove_faculty_mba_slno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_pharamacy',
            name='slno',
        ),
    ]
