# Generated by Django 5.1 on 2024-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0031_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(default=None, upload_to='Home/banners/video'),
            preserve_default=False,
        ),
    ]
