# Generated by Django 5.1 on 2024-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0032_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Home/banners/Images'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Home/banners/video'),
        ),
    ]
