# Generated by Django 5.1 on 2024-09-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0033_alter_banner_image_alter_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsandactivites',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='EventsandActivites/Images/'),
        ),
    ]
