# Generated by Django 5.1 on 2024-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0034_alter_eventsandactivites_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='sub_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Banner', 'Banner')], default='Image', max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryvideos',
            name='sub_type',
            field=models.CharField(choices=[('Video', 'Video')], default='Videos', max_length=50),
        ),
    ]
