# Generated by Django 5.1 on 2025-02-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0035_alter_galleryimages_sub_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('admission_form', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Library_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=200)),
                ('titles', models.IntegerField(blank=True, null=True)),
                ('volumes', models.IntegerField(blank=True, null=True)),
                ('journals', models.IntegerField(blank=True, null=True)),
                ('international_journals', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_particulars', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mba_Faculty_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_image', models.ImageField(blank=True, null=True, upload_to='Mba_Faculty/Images/')),
                ('faculty_name', models.CharField(max_length=50)),
                ('faculty_designation', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='collegeupdates',
            name='updates_files',
            field=models.FileField(blank=True, null=True, upload_to='Home/CollegeUpdates'),
        ),
        migrations.AddField(
            model_name='collegeupdates',
            name='updates_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='designation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='location',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='collegeupdates',
            name='updates_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
