# Generated by Django 5.1 on 2025-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboardapp', '0036_course_admissions_importantsites_library_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_admissions',
            name='admission_form',
        ),
        migrations.AddField(
            model_name='course_admissions',
            name='admission_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
